services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: api-final
    ports:
      - "${BACKEND_PUBLIC_PORT}:8080"
    environment:
      - DOTNET_ENVIRONMENT=${BACKEND_ENVIRONMENT}
      - Cors__AllowedOrigins__0=http://localhost:${FRONTEND_PUBLIC_PORT}
      - ConnectionStrings__ApplicationDatabaseConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - MeteoriteSyncCronSchedule=${SYNC_CRON_SCHEDULE}
      - Cache__Provider=${CACHE_PROVIDER}
      - Cache__Redis__Configuration=${REDIS_CONNECTION}
    networks:
      - test-task-network

  migrator:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: migrator-final
    entrypoint: ["./efbundle"] 
    command: --connection "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - test-task-network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        - VITE_API_URL=http://localhost:${BACKEND_PUBLIC_PORT}
    ports:
      - "${FRONTEND_PUBLIC_PORT}:80"
    restart: always

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - test-task-network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "${POSTGRES_PUBLIC_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql
      - ./data/pg_init:/docker-entrypoint-initdb.d
    networks:
      - test-task-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  test-task-network:
   driver: bridge
